### ISSUE TITLE
Split ZIO-NIO into two submodules

### ISSUE THREAD

**Issue by jczuchnowski** [zio/zio-nio#121]
Because of the growing desire to improve the NIO API and make it more ZIO-native, the idea appeared to split the project into two submodules:

- zio-nio-core - an unopinionated wrapper on Java NIO (in line with the original project intention)
- zio-nio - opinionated improvements on zio-nio-core exploring full potential of ZIO (eg. extensive usage of ZManaged)

Some parts are already opinionated and need to be "downgraded" in zio-nio-core:

- [x] AsynchronousChannnel
- [x] AsynchronousChannnelGroup
- [x] AsynchronousFileChannel
- [x] DatagramChannel
- [x] FileChannel
- [x] SelectableChannel
- [x] file/ package

**Comment by pshemass** [comment]
@jczuchnowski this is done I'm closing this.
