### ISSUE TITLE
Create microsite using mdoc

### ISSUE THREAD

**Issue by mijicd** [zio/zio-nio#15]
Document the library design and usage patterns using [mdoc](https://github.com/scalameta/mdoc).

**Comment by mtsokol** [comment]
Hi, I would like to start working on it. Can I follow zio microsite?

**Comment by mtsokol** [comment]
Hi, have you started working on this one? Do you mind if I write some of it? I would like to learn zio-nio a bit and start by writing some usage examples.

**Comment by mijicd** [comment]
@mtsokol No significant progress on my side. You're welcome to pick this one up, let me know if you need any help! You're free to use `zio` and `zio-actors` as examples.

**Comment by mijicd** [comment]
Closed in #20 .
