### ISSUE TITLE
Refactor tests

### ISSUE THREAD

**Issue by mijicd** [zio/zio-nio#165]
Most of the tests use assertions of the following form `assert(predicate)(isTrue)`. While this is certainly a possible thing to do, we should consider utilizing the full power of `zio-test`.

**Comment by alphaho** [comment]
I think I can work on this one =D

**Comment by devcdcc** [comment]
Hi @mijicd wouldn't it be fine if we close this PR?

**Comment by mijicd** [comment]
It would, that's what happen when you don't link the ticket in the PR :).
