### ISSUE TITLE
Use withCompletionHandler from Java interop

### ISSUE THREAD

**Issue by sideeffffect** [zio/zio-nio#18]
Use the helper method `withCompletionHandler` from `zio`/`interop-java` instead of `AsynchronousChannel.wrap` once the PR has been merged

https://github.com/zio/interop-java/pull/17

(related to https://github.com/zio/zio-nio/pull/8 )

**Comment by quelgar** [comment]
Oh nice, I had no idea that existed. Doesn't really seem like it belongs in interop-java, since it's only used in nio, but might as well use it if it's there.

**Comment by sideeffffect** [comment]
the PR has been merged btw

`interop-java` is just that, interop with Java, so anything JRE (up to version 8 at this point, so now `Flow`) should be a fair game there.

actually what would you guys think about merging the `nio` stuff there too? We might as well have just one interop library for Java -- since both `java.util.concurrent` and `java.nio` come with JRE, there wouldn't be any aditional dependency

**Comment by quelgar** [comment]
Personally I don't see a problem merging, it probably comes down to what scope the interop-java project is aiming for.

**Comment by sideeffffect** [comment]
we could potentially have `java-interop` and `java-interop-11` (`Flow`, and other constructs not present in JRE <= 8 could be there)

**Comment by pshemass** [comment]
this is done by #116 thanks @sideeffffect
