### ISSUE TITLE
Better representation for SelectionKey operations

### ISSUE THREAD

**Issue by jczuchnowski** [zio/zio-nio#21]
Right now the operations of SelectionKey are represented as Integer constants - SelectionKey.OP_ACCEPT, SelectionKey.OP_CONNECT, SelectionKey.OP_READ, SelectionKey.OP_WRITE. Methods interestOps and readyOps need to deal with that. It could be represented better as a Set of case objects.

Issue moved from https://github.com/scalaz/scalaz-nio/issues/87

**Comment by quelgar** [comment]
Thanks @shevv920 ! 👍
