### ISSUE TITLE
Introduce zio.nio.channels.FileLock wrapper

### ISSUE THREAD

**Issue by mtsokol** [zio/zio-nio#22]
While working on `AsynchronousFileChannel` I came across such case:

```scala
for {
  file <- AsynchronousFileChannel.open(Paths.get("./test.txt"), Set.empty)
  fileLock <- file.lock
  //sth
  _ = fileLock.release()  //plain NIO API
}
```

I think that for consistency it would be valuable to  perform `FileLock` operations  inside `ZIO` effect, like in `lock`. I would introduce `FileLock` wrapper in `ZIO` for this. 
What do you think?

**Comment by sinoz** [comment]
Wouldn't it be better to lift your effect into a 'locked' operation instead? This way the lock is guaranteed to be released.

```scala
  def locked[A](effect: IO[Exception, A]): IO[Exception, A] =
    lock.bracket(l => UIO.effectTotal(l.release()))(_ => effect)
```

```scala
val myFunOperation: ZIO[AsynchronousFileChannel, Exception, Unit] =
  ???

val gonnaOpenFile = for {
  file <- AsynchronousFileChannel.open(Paths.get("./test.txt"), Set.empty)
  _   <- file.locked(myFunOperation)
} yield ()
```

**Comment by mtsokol** [comment]
@sinoz the `locked` accurately solves my case, thank you.

Although I think that `FileLock` wrapper still can be introduced. So `AsynchronousFileChannel` provides all methods from `java.nio` like `size` or `isOpen`, what is in PR is same wrapper for `FileLock` API. What do you think? 

Also how about introducing such `locked` for `AsynchronousFileChannel`? 
Just like `Semaphore` has `acquire` and `release`, but it also provides `withPermit[R, E, A](task: ZIO[R, E, A])` which combines it.

**Comment by sinoz** [comment]
@mtsokol I think adding the wrapper would be fine but it shouldn't be exposed and thus remain an internal API. The `locked` function I provided (or something similar, should someone else come up with a better alternative) should be the de facto standard for users to make use of to guarantee resource safety

**Comment by mtsokol** [comment]
Done in #23
