### ISSUE TITLE
Make AsynchronousChannelGroup use ZIO's Executor

### ISSUE THREAD

**Issue by jczuchnowski** [zio/zio-nio#29]
There's a set of factory methods for `AsynchronousChannelGroup` that use external ExecutorService and thread pools. As ZIO's philosophy is to simplify the correct  usage of thread pools it would be good if these methods used ZIO's non-blocking Executor instead. 
This executor can be obtained through `ZIO.runtime`. 
We'll also need a ZIO Executor method similar to `asEC` that will return the representation as `ExecutionContextExecutorService`.

The question remains if the old methods should stay in case there's a need to use yet another thread pool.

**Comment by PawelGizka** [comment]
I take this

**Comment by quelgar** [comment]
There's also an `AsynchronousFileChannel.open` method that takes a Java `ExecutorService` currently.
