### ISSUE TITLE
Use ZManaged for resource management

### ISSUE THREAD

**Issue by quelgar** [zio/zio-nio#30]
Many NIO objects require strict lifecycle management using error-prone methods like `close` and `release`, it would be great to use `ZManaged` for these and remove all such `close` methods.

TODO:

- [x] AsynchronousByteChannel
- [x] AsynchronousSocketChannel
- [x] AsynchronousServerSocketChannel
- [x] AsynchronousFileChannel
- [x] FileChannel
- [x] GatheringByteChannel
- [x] ScatteringByteChannel
- [x] SelectableChannel 
- [x] Selector

**Comment by mijicd** [comment]
cc @svroonland

**Comment by jczuchnowski** [comment]
Went over the code and here's a TODO list:

- [ ] AsynchronousByteChannel
- [ ] AsynchronousServerSocketChannel
- [ ] AsynchronousFileChannel
- [ ] GatheringByteChannel
- [ ] ScatteringByteChannel
- [ ] SelectableChannel 
- [ ] Selector

**Comment by svroonland** [comment]
See #34 for a start

**Comment by jczuchnowski** [comment]
Yeah, I got it. I'll mark it on the list once it's merged.

**Comment by pshemass** [comment]
I think we are done with this
