### ISSUE TITLE
Scala 3 compatibility

### ISSUE THREAD

**Issue by adamw** [zio/zio-nio#352]
sttp is waiting :)

**Comment by ithinkicancode** [comment]
@adamw In my last PR for zio-nio, I updated the dotty version to 3.0.0. I didn't realize this: apparently that generated a Scala 3 artifact for zio-nio (that makes sense; all I did was removing the RC tag from the version, I'm no expert on migrating a project to Scala 3, not yet at least). The artifact has been published. Do you want to give it a go and see if it actually works? :)

https://repo1.maven.org/maven2/dev/zio/zio-nio_3/1.0.0-RC11/

**Comment by adamw** [comment]
Indeed, it's there, and it works. Turns out I enabled it already. Thank you!
