### ISSUE TITLE
Replace testz with zio tests

### ISSUE THREAD

**Issue by mijicd** [zio/zio-nio#53]
`testz` doesn't seem to be maintained anymore, and it doesn't allow us to support 2.11 (which I admit is a debatable goal). While zio tests is under development, it is already usable and maintained by our community, therefore I'd recommend unifying the tool chains wherever possible :).

**Comment by mtsokol** [comment]
There's already zio test with examples in core, so I will start it moving to it if nobody is working on it now.

**Comment by mtsokol** [comment]
Addressed in #64
