### ISSUE TITLE
Add support for 2.13

### ISSUE THREAD

**Issue by mijicd** [zio/zio-nio#54]
Investigate the necessary changes and apply them. Once they're in place, make sure to reflect them in CircleCI configuration.

**Comment by tomasherman** [comment]
im gonna take this on as part of zio hackathon ;)

**Comment by tomasherman** [comment]
so the only blocker is `interop-java` dependency that is not released for 2.13 so far - gonna attempt to do that

**Comment by tomasherman** [comment]
`interop-java` is released ... once it's out of staging and available, it should be straight forward to finish this of
