### ISSUE TITLE
Buffer.byte - `NoSuchMethodError: zio.Chunk.toArray`

### ISSUE THREAD

**Issue by mtsokol** [zio/zio-nio#99]
Hi, 

I've encountered an issue with ZIO-NIO (or ZIO).
I'm using RC-15 for ZIO an 0.2.1 for ZIO-NIO. In my worksheet such code fails:

```scala
import zio.DefaultRuntime

val chunk = zio.Chunk.fromArray(Array(1,2,3)).map(_.toByte)

val runtime = new DefaultRuntime {}

val _ = chunk.toArray

runtime.unsafeRun(zio.nio.Buffer.byte(chunk))
```

The last one line fails with: 

```
Fiber failed.
An unchecked error was produced.
java.lang.NoSuchMethodError: zio.Chunk.toArray()Ljava/lang/Object;
at zio.nio.Buffer$.$anonfun$byte$3(Buffer.scala:108)
at zio.internal.FiberContext.evaluateNow(FiberContext.scala:280)
at zio.Runtime.unsafeRunAsync(Runtime.scala:93)
at zio.Runtime.unsafeRunAsync$(Runtime.scala:79)
...
```

Then switching ZIO version to RC-13 (so the one that ZIO-NIO is using) the issue does not occur.
Between these versions the signature of `toArray` has changed a bit.

Should we inspect it on ZIO-NIO side or ZIO's Chunk?

Maybe we should make a release that depends on RC-15 also?

**Comment by pshemass** [comment]
@mtsokol zio-nio ```master``` is on RC-15 (https://github.com/zio/zio-nio/blob/master/project/BuildHelper.scala) could you check if this is problem with ```master``` branch by building it locally? if this will work I can push new version with updated ZIO

**Comment by mtsokol** [comment]
@pshemass I've just checked it with local build and with current master this error does not occur. 
If you don't mind pushing new release it would be great! 
Thanks for help.

Otherwise this week at Berlin Hackathon there might be a new release (hopefully 1.0).

**Comment by mtsokol** [comment]
The version has been bumped during Berlin Hackathon and the issue does not occur anymore.
